metallb:
  controller:
    resources:
      limits:
        cpu: 0m
        memory: 96Mi
      requests:
        cpu: 0m
        memory: 0Mi
  speaker:
    resources:
      limits:
        cpu: 0m
        memory: 80Mi
      requests:
        cpu: 0m
        memory: 0Mi
    frr:
      resources:
        limits:
          cpu: 0m
          memory: 64Mi
        requests:
          cpu: 0m
          memory: 0Mi
    reloader:
      resources:
        limits:
          cpu: 0m
          memory: 16Mi
        requests:
          cpu: 0m
          memory: 0Mi
    frrMetrics:
      resources:
        limits:
          cpu: 0m
          memory: 16Mi
        requests:
          cpu: 0m
          memory: 0Mi
